name: Build Enigma Firmware
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Firmware
        run: |
          west init -l config
          west update
          west build -p auto -b seeeduino_xiao_ble -d build/enigma -- -DSHIELD=enigma -DZMK_CONFIG="${{ github.workspace }}/config"
      - name: Rename Firmware
        run: |
          mv build/enigma/zephyr/zmk.uf2 enigma.uf2
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: enigma-firmware
          path: |
            *.uf2
