name: Build Enigma Firmware
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          # Westと依存関係をインストール
          pip install west
          # Zephyr SDKの依存パッケージをインストール
          sudo apt-get update
          sudo apt-get install -y ninja-build gperf ccache dfu-util device-tree-compiler
      - name: Install Zephyr SDK
        run: |
          # Zephyr SDKをダウンロードしてインストール
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.5/zephyr-sdk-0.16.5_linux-x86_64.tar.xz
          mkdir -p ~/zephyr-sdk
          tar -xf zephyr-sdk-0.16.5_linux-x86_64.tar.xz -C ~/zephyr-sdk --strip-components=1
          # ツールチェインのセットアップ
          ~/zephyr-sdk/setup.sh -t arm-zephyr-eabi
      - name: Initialize and update West
        run: |
          west init -l config
          west update
      - name: Build firmware
        run: |
          # Zephyr SDKのパスを環境変数に設定
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=~/zephyr-sdk
          west build -s zmk/app -p auto -b seeeduino_xiao_ble -d build/enigma -- -DSHIELD=enigma -DZMK_CONFIG="${{ github.workspace }}/config"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: enigma-firmware
          path: |
            build/enigma/zephyr/*.uf2
