name: Build Enigma Firmware
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install west and dependencies
        run: |
          pip install west
          west init -l config
          west update
      - name: Build firmware
        run: |
          west build -p auto -b seeeduino_xiao_ble -d build/enigma -- -DSHIELD=enigma -DZMK_CONFIG="${{ github.workspace }}/config"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: enigma-firmware
          path: |
            build/enigma/zephyr/*.uf2
