name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3-pip git
          pip3 install west

      - name: Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/zephyr-sdk-0.16.1_linux-x86_64.tar.xz
          mkdir -p ~/zephyr-sdk
          tar -xJf zephyr-sdk-0.16.1_linux-x86_64.tar.xz -C ~/zephyr-sdk --strip-components=1
          ~/zephyr-sdk/setup.sh -t all
          echo "export ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "export ZEPHYR_SDK_INSTALL_DIR=~/zephyr-sdk" >> $GITHUB_ENV

      - name: Initialize and update west
        run: |
          west init -l config
          west update

      - name: Build ZMK firmware
        env:
          ZEPHYR_BASE: ${{ github.workspace }}/zephyr
          CMAKE_PREFIX_PATH: ${{ env.ZEPHYR_BASE }};~/zephyr-sdk
        run: |
          west build -s zmk/app -p auto -b seeeduino_xiao_ble -d build/enigma -- -DSHIELD=enigma -DZMK_CONFIG="${{ github.workspace }}/config"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/enigma/zephyr/zmk.uf2