name: Build ZMK Firmware
on: [push]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      extra_cmake_args: -DZMK_CONFIG="${{ github.workspace }}/config"
