name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3-pip git gcc g++ device-tree-compiler libyaml-dev
          pip3 install west

      - name: Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/zephyr-sdk-0.16.1_linux-x86_64.tar.xz
          mkdir -p ~/zephyr-sdk
          tar -xJf zephyr-sdk-0.16.1_linux-x86_64.tar.xz -C ~/zephyr-sdk --strip-components=1
          cd ~/zephyr-sdk
          ./setup.sh -t all -h

      - name: Set up Zephyr environment
        run: |
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=/home/runner/zephyr-sdk" >> $GITHUB_ENV
          echo "PATH=/home/runner/zephyr-sdk/bin:$PATH" >> $GITHUB_ENV
          echo "ZEPHYR_BASE=${{ github.workspace }}/zephyr" >> $GITHUB_ENV

      - name: Initialize and update west
        run: |
          west init -l config
          west update
          # Zephyrの依存関係を解決するために追加
          cd ${{ github.workspace }}/zephyr
          west init -l
          west update

      - name: Debug Zephyr environment
        run: |
          echo "ZEPHYR_BASE: $ZEPHYR_BASE"
          echo "ZEPHYR_SDK_INSTALL_DIR: $ZEPHYR_SDK_INSTALL_DIR"
          ls -la ${{ github.workspace }}/zephyr
          find ${{ github.workspace }} -name "ZephyrConfig.cmake" -o -name "zephyr-config.cmake"
          west -vv status

      - name: Build ZMK firmware
        run: |
          west build -s ${{ github.workspace }}/zmk/app -p auto -b seeeduino_xiao_ble -d build/enigma -- -DSHIELD=enigma -DZMK_CONFIG="${{ github.workspace }}/config"