name: Build Enigma Firmware
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # checkoutも最新バージョンに更新
      - name: Build firmware
        uses: zmkfirmware/zmk-action@main  # zmk-build-actionの代替として仮定
        with:
          board: seeeduino_xiao_ble
          shield: enigma
          config: config/enigma.conf
          keymap: config/enigma.keymap
      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # v3からv4に更新
        with:
          name: enigma-firmware
          path: |
            *.uf2
